[versions]
activity = "1.10.1"
androidxJunit = "1.2.1"
appcompat = "1.7.0"
espresso = "3.6.1"
junit = "4.13.2"
material = "1.12.0"
playServicesMaps = "19.0.0"
recyclerview = "1.4.0"
volley = "1.2.1"

[libraries]
activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidxJunit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
playServicesMaps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }