[versions]
gradle = "8.5.1"
kotlin = "2.0.0"
appcompat = "1.7.0"
cardview = "1.0.0"
recyclerview = "1.3.2"
multidex = "2.0.1"
secretsGradlePlugin = "2.0.1"
volley = "1.2.1"
lifecycle = "2.8.4"
mapsKtx = "5.1.0"
easypermissions = "3.0.0"
junit = "4.13.2"
androidxJunit = "1.2.1"
espresso = "3.6.1"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinStdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk7", version.ref = "kotlin" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
secretsGradlePlugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
lifecycleRuntimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
mapsKtx = { group = "com.google.maps.android", name = "maps-ktx", version.ref = "mapsKtx" }
easypermissions = { group = "pub.devrel", name = "easypermissions", version.ref = "easypermissions" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidxJunit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }