[versions]
compileSdk = "34"
gradle = "8.5.2"
minSdk = "21"
secretsGradlePlugin = "2.0.1"
targetSdk = "34"
versionCode = "1"
versionName = "1.0"
appcompat = "1.7.0"
playServicesMaps = "19.0.0"
places = "3.5.0"
volley = "1.2.1"
kotlinBom = "2.0.0"
junit = "4.13.2"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
playServicesMaps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
places = { group = "com.google.android.libraries.places", name = "places", version.ref = "places" }
secretsGradlePlugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinBom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlinBom" }
