[versions]
compileSdk = "36"
gradle = "8.10.1"
material = "1.12.0"
minSdk = "23"
secretsGradlePlugin = "2.0.1"
targetSdk = "36"
versionCode = "1"
versionName = "1.0"
appcompat = "1.7.1"
playServicesMaps = "19.2.0"
places = "4.3.1"
volley = "1.2.1"
kotlinBom = "2.2.20"
junit = "4.13.2"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
playServicesMaps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
places = { group = "com.google.android.libraries.places", name = "places", version.ref = "places" }
secretsGradlePlugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinBom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlinBom" }
