[versions]
compileSdk = "34"
gradle = "8.5.2"
minSdk = "21"
secretsGradlePlugin = "2.0.1"
targetSdk = "34"
versionCode = "1"
versionName = "1.0"
appcompat = "1.7.0"
playServicesMaps = "19.0.0"
kotlinBom = "2.0.0"
junit = "4.13.2"
androidxTestExtJunit = "1.2.1"
espressoCore = "3.6.1"
javaVersion = "21"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
playServicesMaps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
kotlinBom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlinBom" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidxTestExtJunit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
secretsGradlePlugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
