version: 1
update_configs:
    - package_manager: "java:gradle"
      directory: "./ApiDemos/java/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./ApiDemos/kotlin/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./WearOS/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./tutorials/java/CurrentPlaceDetailsOnMap/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./tutorials/kotlin/CurrentPlaceDetailsOnMap/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./tutorials/java/MapWithMarker/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./tutorials/kotlin/MapWithMarker/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./tutorials/java/Polygons/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./tutorials/kotlin/Polygons/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./tutorials/java/StyledMap/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./snippets/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"
