# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Lint and Upload SARIF

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Check documentation versions
        run: python3 scripts/update_docs_versions.py --check

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run Android Lint
        run: |
          ./gradlew :ApiDemos:kotlin-app:lintDebug
          ./gradlew :ApiDemos:java-app:lintDebug
          ./gradlew :ApiDemos:common-ui:lintDebug
          ./gradlew :snippets:app:lintGmsDebug
          ./gradlew :snippets:app-utils:lintDebug
          ./gradlew :snippets:app-utils-ktx:lintDebug
          ./gradlew :snippets:app-places-ktx:lintDebug
          ./gradlew :snippets:app-ktx:lintDebug
          ./gradlew :snippets:app-compose:lintDebug
          ./gradlew :WearOS:Wearable:lintDebug
          ./gradlew :FireMarkers:app:lintDebug

      - name: Upload SARIF for ApiDemos:kotlin-app
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ApiDemos/project/kotlin-app/build/reports/lint-results-debug.sarif
          category: ApiDemos-kotlin-app

      - name: Upload SARIF for ApiDemos:java-app
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ApiDemos/project/java-app/build/reports/lint-results-debug.sarif
          category: ApiDemos-java-app

      - name: Upload SARIF for ApiDemos:common-ui
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ApiDemos/project/common-ui/build/reports/lint-results-debug.sarif
          category: ApiDemos-common-ui

      - name: Upload SARIF for snippets:app
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snippets/app/build/reports/lint-results-debug.sarif
          category: snippets-app

      - name: Upload SARIF for snippets:app-utils
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snippets/app-utils/build/reports/lint-results-debug.sarif
          category: snippets-app-utils

      - name: Upload SARIF for snippets:app-utils-ktx
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snippets/app-utils-ktx/build/reports/lint-results-debug.sarif
          category: snippets-app-utils-ktx

      - name: Upload SARIF for snippets:app-places-ktx
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snippets/app-places-ktx/build/reports/lint-results-debug.sarif
          category: snippets-app-places-ktx

      - name: Upload SARIF for snippets:app-ktx
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snippets/app-ktx/build/reports/lint-results-debug.sarif
          category: snippets-app-ktx

      - name: Upload SARIF for snippets:app-compose
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snippets/app-compose/build/reports/lint-results-debug.sarif
          category: snippets-app-compose

      - name: Upload SARIF for WearOS:Wearable
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: WearOS/Wearable/build/reports/lint-results-debug.sarif
          category: WearOS-Wearable

      - name: Upload SARIF for FireMarkers:app
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: FireMarkers/app/build/reports/lint-results-debug.sarif
          category: FireMarkers-app