on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          command: manifest
          token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
          
      - name: Checkout
        uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
            token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}

      - name: set up Java 21
        uses: actions/setup-java@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build APKs
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "Generating ApiDemos (Java) APKs"
          cd $GITHUB_WORKSPACE/ApiDemos/project/
          ./gradlew assemble
          cp ./java-app/build/outputs/apk/debug/java-app-debug.apk $GITHUB_WORKSPACE/ApiDemos-java-debug.apk
  
          echo "Generating Kotlin (Kotlin) APKs"
          ./gradlew assemble
          cp ./kotlin-app/build/outputs/apk/debug/kotlin-app-debug.apk $GITHUB_WORKSPACE/ApiDemos-kotlin-debug.apk

      - name: Upload Release Artifacts
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} ./ApiDemos-java-debug.apk ./ApiDemos-kotlin-debug.apk
